version = "v4"
action_loss = "l1"
batch_size = 64
steps = 100000
lr = 1e-4
seed = 0
beta = 0.01
beta_start = 0.001
beta_warmup_steps = 0
checkpoint_every = 2000
use_z = true
image_keys = ["agentview_image", "robot0_eye_in_hand_image"]

[tensorboard]
activations = false
batch_metrics = true
denorm_l1 = true
epoch_metrics = true
eval = true
hyperparams = true
latent = true
lr = true
optimizer = false
ranges = false
sensitivity = false
throughput = true
timing = true
